### GET
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/6027e041969b5e153ca39d8f

### DELETE
DELETE http://localhost:3001/api/notes/6027d3d98a914033048433a2

### POST
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "sample",
    "important": true,
    "date": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### PUT
PUT http://localhost:3001/api/notes/6027e041969b5e153ca39d8f HTTP/1.1
content-type: application/json

{
    "content": "sample1234",
    "important": true
}